# Generated by Django 4.2.20 on 2025-03-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_erp', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_erp.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_erp.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_erp.educationuser')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_erp.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education_erp.educationuser')),
            ],
        ),
    ]
